[DOCS] update readme to reflect default k8s events handling
logdna/logdna-agent-v2 pull request #364
Opened 2022-07-04 13:23 UTC by afirth

the readme is contradictory - the default value is never

/fixes 235

2022-07-07 21:56 UTC, stsantilena approved these changes

2022-07-08 08:18 UTC, c-nixon commented
@logdnabot test this please

2022-07-18 07:42 UTC, c-nixon commented
@logdnabot test this please

2022-07-19 19:25 UTC, c-nixon commented
@logdnabot test this please

2022-07-19 19:29 UTC, dkhokhlov requested changes

2022-07-19 19:29 UTC, dkhokhlov commented on docs/README.md
"using on of these" - typo?

2022-07-19 19:45 UTC, c-nixon commented on docs/README.md
Looks like that's a pre-existing one

2022-07-19 19:47 UTC, merged

2022-07-19 19:51 UTC, c-nixon commented
Thanks for the contribution! Sorry for the delay. Jenkins wasn't acknowledging the activation comments