[WIP] Windows File Handle Leak
logdna/logdna-agent-v2 pull request #442
Opened 2022-11-04 23:47 UTC by stsantilena

2022-11-14 17:10 UTC, dkhokhlov requested changes

2022-11-14 17:10 UTC, dkhokhlov commented on common/fs/src/cache/mod.rs
>      async fn filesystem_delete_file() -> io::Result<()> {
this is basic test to verify on windows for this fix. shall pass.

2022-11-14 17:10 UTC, dkhokhlov commented on common/notify_stream/src/lib.rs
>      async fn test_unwatch_if_exists() {
this is basic test to verify on windows for this fix. shall pass.

2022-11-29 18:18 UTC, stsantilena commented on common/notify_stream/src/lib.rs
>      async fn test_create_write_delete() -> io::Result<()> {
Added additional, Windows specific test for this.

2022-12-21 21:30 UTC, stsantilena commented
The fixes for this were included in #453. Closing this out.

2022-12-21 21:30 UTC, closed without merging