Reduce k8s metadata memory use
logdna/logdna-agent-v2 pull request #493
Opened 2023-04-13 12:08 UTC by c-nixon

This reduces the k8s metadata watcher's memory footprint by only tracking the pod metadata rather than the entire pod spec

2023-04-13 14:10 UTC, dkhokhlov commented on common/k8s/src/middleware/metadata.rs
> +        let watched = StreamBackoff::new(watcher, ExponentialBackoff::default());
@jakedipity 

This StreamBackoff may be our suspect in the missing k8s meta issue. The stream processing has silent errors (no logging).

> After any Err is emitted, the stream is paused for Backoff::next_backoff. The Backoff is reset on any Ok value. If Backoff::next_backoff returns None then the backing stream is given up on, and closed.

2023-07-31 16:32 UTC, dkhokhlov approved these changes
lgtm

2023-07-31 17:16 UTC, jakedipity commented on common/k8s/src/middleware/metadata.rs
> +                pod.managed_fields_mut().clear();
Clearing managed_fields happens twice, once here and again on L384. You can remove the `map_ok` on L384

2023-07-31 17:47 UTC, jakedipity requested changes
Just one instance of duplicate code

2023-08-01 18:14 UTC, jakedipity approved these changes

2023-08-02 07:58 UTC, merged